runtime: python27
api_version: 1
threadsafe: true

service: blockchain-101

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

- url: /img
  static_dir: img

